name: UnlimitedRecipeLegacyLegacy
version: 1.0.0
author: Alexzvn
main: dev.alexzvn.recipe.UnlimitedRecipeLegacy
depend: [NBTAPI]

api-version: 1.10

commands:
  recipe:
    aliases: [rp]
    descriptions: Base recipe command

permissions:
  recipe.admin:
    description: Gives access to everything!
    children:
      recipe.admin.show: true
      recipe.admin.edit: true
      recipe.admin.delete: true
      recipe.admin.create: true
