name: UnlimitedRecipe
version: 1.0.0
author: Alexzvn
main: dev.alexzvn.recipe.UnlimitedRecipe

api-version: 1.16

commands:
  recipe:
    aliases: [rp]
    descriptions: Base recipe command

permissions:
  recipe.admin:
    description: Gives access to everything!
    children:
      recipe.admin.show: true
      recipe.admin.edit: true
      recipe.admin.create: true
